name: Gerar APK SanDriv

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle 8.7
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Gerar APK SanDriv
        run: gradle :app:assembleDebug --stacktrace

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: SanDriv-APK
          path: app/build/outputs/apk/debug/app-debug.apk
